// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5eTDx3f2bPATU55NTzQ31vIrIwtB-mKg',
    appId: '1:193227456826:web:21d699b4637bd021235003',
    messagingSenderId: '193227456826',
    projectId: 'quickstart-1592239740813',
    authDomain: 'quickstart-1592239740813.firebaseapp.com',
    storageBucket: 'quickstart-1592239740813.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa1J7BK_8w9_Fdr5hArhlj38fu8SI7mx8',
    appId: '1:193227456826:android:22fba1b9e8320e21235003',
    messagingSenderId: '193227456826',
    projectId: 'quickstart-1592239740813',
    storageBucket: 'quickstart-1592239740813.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGPD7khniIwJj8PEgTz4OM-yIyCl4vRKo',
    appId: '1:193227456826:ios:2512453b9a432ab1235003',
    messagingSenderId: '193227456826',
    projectId: 'quickstart-1592239740813',
    storageBucket: 'quickstart-1592239740813.appspot.com',
    iosBundleId: 'com.example.toto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGPD7khniIwJj8PEgTz4OM-yIyCl4vRKo',
    appId: '1:193227456826:ios:93cd2fa81d4c8cb0235003',
    messagingSenderId: '193227456826',
    projectId: 'quickstart-1592239740813',
    storageBucket: 'quickstart-1592239740813.appspot.com',
    iosBundleId: 'com.example.toto.RunnerTests',
  );
}
